# Generated by Django 4.2.9 on 2024-01-18 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_calendar_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_owner_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='users',
            field=models.ManyToManyField(default=[], related_name='calendar_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
