# Generated by Django 4.2.9 on 2024-01-12 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'custom_user', 'verbose_name_plural': 'custom_users'},
        ),
    ]
